spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}
  context-path: /${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry:  false
  serviceUrl:
    defaultZone:  http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: 'OFF'
        discovery:  'OFF'