spring:
  application:
    name: eureka-server
  jmx:
    default-domain: ${spring.application.name}


server:
  port: ${PORT:8761}
  context-path: /${spring.application.name}

eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty:  0
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry:  false
  serviceUrl:
    defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka-server/eureka/

logging:
  level:
    com:
      netflix:
        eureka: 'OFF'
        discovery:  'OFF'